---
abstract: 'Advanced object construction for DBIx::Simple!'
author:
  - 'Красимир Беров <berov@cpan.org>'
build_requires:
  DBD::SQLite: 1.29
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Simple-Class
no_index:
  directory:
    - t
    - inc
requires:
  DBIx::Simple: 1.33
  Test::More: 0
version: 0.60
